### ISSUE TITLE
Width get reset every time a file is opened

### ISSUE THREAD

**Issue by franleplant** [jaypei/emacs-neotree#129]
Hi!
    I manually adjust the width of the neotree but when I open a file it get's reset to it's original size (smaller), is there any solution for this?

Thanks a lot!
Fran

**Comment by golbin** [comment]
I set like below;

```
(setq neo-window-width 25)
```

**Comment by liuzhen** [comment]
should remember it?

**Comment by feluxe** [comment]
I have to resize the neotree window quite often to find a good ratio between the neotree window and the opened buffer on my small laptop screen. I do that by dragging the window separator with my mouse. As soon as I switch to another buffer the width is set back to the default value. This becomes nasty when I work on multiple files simultaneously, because I have to resize the window every time I switch from file to file. 

The default behaviour in other editors/IDEs is to remember the size, which I think makes sense.

**Comment by malloryerik** [comment]
It seems like the answer is here:
https://github.com/jaypei/emacs-neotree/issues/262

**Comment by palikar** [comment]
Fixed in 6e3ae07b08d4dd218c119e91a101d7e7ed6ef4d9
