### ISSUE TITLE
Modern sidebar with split windows

### ISSUE THREAD

**Issue by duff** [jaypei/emacs-neotree#135]
Hi there,

If I open up a split window with neotree using the new default of modern sidebar, things look great to start:

![_neotree_](https://cloud.githubusercontent.com/assets/2437/10431130/543686e8-70d1-11e5-9ac0-e28bfbee6527.jpg)

But if I toggle the neotree such that it's no longer shown and then I toggle it back to being shown, it no longer acts like a modern sidebar:

![_neotree_](https://cloud.githubusercontent.com/assets/2437/10431149/76b20184-70d1-11e5-94f1-ad2be0b04309.jpg)

since it's now split.  I'm having some difficulty discerning what this issue might be caused by.  I thought I'd mention it here in case anyone might have ideas as to where I might look.  Thanks!

**Comment by jasondf** [comment]
If I remember correctly, the same thing happened with speedbar, and I don't know the reason either.

**Comment by sfdi** [comment]
Having the same issue. To clarify, I show/hide neotree using the ```(global-set-key [f8] 'neotree-toggle)``` binding. The expected behavior is for neotree to span the entire frame vertically. Instead, it spans only the window that has focus. This makes the plugin pretty useless; in most horizontally split windows the sidebar is too small to be useful without lots of scrolling...

**Comment by duff** [comment]
Hi @palikar - I've switched back to Vim... so it's not an issue for me personally anymore. I can close this one out for now. Feel free to open if anyone is still interested and if it doesn't work in 26.
