### ISSUE TITLE
commit 272f88f broke neotree integration with projectile vc-dir with Mercurial and Darcs. Only works with git

### ISSUE THREAD

**Issue by pbgc** [jaypei/emacs-neotree#307]
After: https://github.com/jaypei/emacs-neotree/commit/272f88f2997a9e839fe6f4b692f1885cb08c69fa

I cannot use neotree opened at projectile project root with projects that use Mercurial or Darcs ...

I get:

```
apply: Symbol’s function definition is void: nil
```

Only git works.

**Comment by palikar** [comment]
Hi @pbgc ,

thanks for the feedback! It seems this is due to kinda of a bug in [all-the-icons](https://github.com/domtronn/all-the-icons.el/). I opened an [issue](https://github.com/domtronn/all-the-icons.el/issues/127) there. I will also see if there is way to get around it on the side of neotree. As ridiculous as it sounds, a quick and dirty way to get by with the bug is to create a file with name ".git" at the root of your project.

**Comment by pbgc** [comment]
Hi @palikar ,

Thank you for your answer and action!
To be able to work with reps using Mercurial and Darcs I cloned this rep, checked out the commit before, and use it instead of the melpa one... But I will try your solution ... just have to see if no tool will get confused by the presence of a .git.
Thanks a lot and hope that all-the-icons can solve this.

**Comment by palikar** [comment]
OK, I've made a new commit on the dev branch that should fix the issue (even if there is no .git file in the root of the project). Could you try it out and let me know if the problem persists.

**Comment by pbgc** [comment]
I tried it (both with git, mercurial and darcs) and it seems the problem went away. thank you !!

**Comment by palikar** [comment]
Awesome!
