### ISSUE TITLE
Minimize (A) NeoTree window after file selected

### ISSUE THREAD

**Issue by ciukstar** [jaypei/emacs-neotree#309]
Minimize (A) NeoTree window after a file is selected and a new buffer opens. This was the default behavior until some updates. How can I enable it again?

**Comment by palikar** [comment]
Hi @ciukstar ,
There is a custom for that now - neo-reset-size-on-open. It is turned off by default because a lot of people were complaining how the feature was annoying. If it, however, works for you, you can turn it back on with: 
```elisp
(setq neo-reset-size-on-open t)
```
Let me know if this is what you meant and I am addressing your problem properly.

**Comment by ciukstar** [comment]
Thanks! `(setq neo-reset-size-on-open t)` worked for me. And not annoying at all.
