### ISSUE TITLE
Issues when used with emacs-purpose extension

### ISSUE THREAD

**Issue by Lugoues** [jaypei/emacs-neotree#95]
https://github.com/bmag/emacs-purpose

When I press F8 the layout goes crazy, left most window splits and neotree shows up in a random window.

**Comment by bmag** [comment]
I came here to report a bug (that is not related to this issue at all), looked in past issues to check if it was reported, instead I found this one. @Lugoues I've found this integration problem independently and implemented a workaround for it one day after you posted this issue (see https://github.com/bmag/emacs-purpose/issues/42), so the issue here can be closed.

**Comment by Abdisalan** [comment]
Closing as stale. If you still have this issue, please open a new issue.
